version: 0.1.7
source: null
info:
  name: 二笔
  version: 0.1.0
  author: 无名氏
  description: 从模板创建
analysis:
  classifier: {}
  degenerator:
    feature:
      提: 横
      捺: 点
    no_cross: false
  selector:
  - 结构完整
  - 根少优先
  - 能连不交
  - 能散不连
  - 全符笔顺
  - 取大优先
form:
  alphabet: qwertyuiopasdfghjklzxcvbnm
  mapping:
    骨: n
    己: a
    丶: n
    鼻: i
    米: z
    '4': o
    镸: j
    A: y
    '3': u
    麦: g
    爿: y
    片: d
    又: h
    其: h
    食: s
    宀: j
    sm-d: d
    wl-n: n
    火: u
    sm-c: c
    疒: a
    攴: r
    舌: j
    尸: w
    龙: d
    sm-yi: k
    见: e
    : y
    鸟: t
    B: k
    瓜: d
    鼠: p
    鱼: c
    自: n
    sm-m: m
    sm-j: j
    癶: j
    广: s
    丬: b
    殳: d
    方: k
    sm-r: r
    日: m
    示: v
    父: l
    犬: f
    言: f
    sm-g: g
    页: h
    羽: q
    土: j
    山: p
    舟: c
    wl-g: g
    sm-t: t
    勹: d
    sm-k: k
    豕: q
    田: r
    文: t
    sm-l: l
    足: a
    厂: b
    wl-i: i
    户: a
    wl-k: k
    sm-w: w
    艮: v
    止: h
    比: n
    sm-p: p
    巾: b
    赤: i
    禾: v
    '2': i
    卜: u
    攵: u
    王: i
    辛: b
    羊: k
    巛: h
    耒: y
    音: r
    鹿: f
    sm-b: b
    欠: k
    E: a
    乙: d
    矢: p
    人: l
    身: n
    '1': e
    黑: r
    厶: c
    wl-f: f
    金: k
    寸: p
    sm-yu: y
    弓: q
    虍: r
    齿: f
    马: f
    手: o
    彡: z
    业: e
    缶: j
    水: e
    木: k
    衣: j
    豆: j
    辰: n
    立: w
    '5': a
    几: r
    夂: u
    sm-f: f
    麻: r
    尢: w
    走: u
    wl-o: o
    女: w
    虫: h
    歹: q
    二: y
    sm-n: n
    耳: g
    风: j
    卤: r
    丿: n
    鬼: g
    母: b
    瓦: w
    青: c
    韦: q
    心: o
    穴: p
    月: w
    子: h
    辶: i
    sm-s: s
    八: p
    冫: c
    疋: a
    囗: g
    车: d
    刀: m
    白: c
    儿: i
    小: j
    皮: g
    覀: c
    D: v
    门: g
    一: r
    里: c
    丨: n
    夕: w
    斗: d
    戈: k
    sm-q: q
    彳: p
    牛: k
    sm-h: h
    血: r
    雨: x
    革: i
    石: x
    爪: h
    工: o
    sm-x: x
    C: i
    sm-0: r
    用: b
    豸: g
    气: i
    聿: v
    大: n
    毛: v
    sm-z: z
    艹: i
    sm-sh: s
    纟: d
    十: a
    罒: y
    隹: q
    sm-ch: c
    彐: g
    力: e
    sm-zh: v
    贝: z
    角: x
    斤: h
    目: t
    口: s
    wl-s: s
    竹: y
  grouping: {}
encoder:
  max_length: 6
  auto_select_length: 2
  sources:
    s6:
      object:
        type: 字根
        rootIndex: -1
      next: null
    s5:
      object:
        type: 字根
        rootIndex: 5
      next: s6
    s0:
      object: null
      next: s1
    s3:
      object:
        type: 字根
        rootIndex: 3
      next: s4
    s2:
      object:
        type: 字根
        rootIndex: 2
      next: s3
    s4:
      object:
        type: 字根
        rootIndex: 4
      next: s5
    s1:
      object:
        type: 字根
        rootIndex: 1
      next: s2
  conditions: {}
  short_code_schemes:
  - prefix: 2
  - prefix: 3
  - prefix: 4
  - prefix: 5
  rules:
  - length_equal: 2
    formula: AaAbBaBb
  - length_equal: 3
    formula: AaBaCaCb
  - length_in_range:
    - 4
    - 10
    formula: AaBaCaZa
optimization:
  objective:
    characters_full:
      duplication: 1.0
    characters_short:
      tiers:
      - top: 500
        duplication: 1.0
        levels:
        - length: 2
          frequency: 0.0
        - length: 3
          frequency: 3.0
        - length: 4
          frequency: 10.0
      - duplication: 1.0
      duplication: 1.0
      key_distribution: 5.0
      pair_equivalence: 20.0
      levels:
      - length: 2
        frequency: -5.0
      - length: 3
        frequency: 1.0
      - length: 4
        frequency: 5.0
      - length: 5
        frequency: 10.0
  constraints:
    elements:
    - element: 乙
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 一
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 丿
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 丨
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 丶
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: '1'
    - element: '2'
    - element: '3'
    - element: '4'
    - element: '5'
    - element: sm-q
    - element: sm-w
    - element: sm-r
    - element: sm-t
    - element: sm-p
    - element: sm-s
    - element: sm-d
    - element: sm-f
    - element: sm-g
    - element: sm-h
    - element: sm-j
    - element: sm-k
    - element: sm-l
    - element: sm-z
    - element: sm-x
    - element: sm-c
    - element: sm-b
    - element: sm-n
    - element: sm-m
    - element: sm-sh
      keys:
      - 's'
    - element: sm-ch
      keys:
      - 'c'
    - element: sm-zh
      keys:
      - 'v'
    - element: sm-yi
      keys:
      - 'k'
    - element: sm-yu
      keys:
      - 'y'
    - element: sm-0
      keys:
      - 'r'
    - element: wl-k
      keys:
      - 'k'
    - element: wl-o
      keys:
      - 'o'
    - element: wl-f
      keys:
      - 'f'
    - element: wl-i
      keys:
      - 'i'
    - element: wl-g
      keys:
      - 'g'
    - element: wl-n
      keys:
      - 'n'
    - element: wl-s
      keys:
      - 's'
  metaheuristic:
    algorithm: SimulatedAnnealing
