version: 0.1.7
source: null
info:
  name: 二笔
  version: 0.1.0
  author: 无名氏
  description: 从模板创建
analysis:
  classifier: {}
  degenerator:
    feature:
      提: 横
      捺: 点
    no_cross: false
  selector:
  - 结构完整
  - 根少优先
  - 能连不交
  - 能散不连
  - 全符笔顺
  - 取大优先
form:
  alphabet: qwertyuiopasdfghjklzxcvbnm
  mapping:
    耳: r
    瓜: v
    其: p
    手: f
    夕: e
    耒: k
    气: k
    欠: z
    舟: e
    音: n
    齿: g
    身: t
    木: q
    '3': u
    角: r
    车: y
    sm-sh: f
    文: s
    sm-x: j
    艮: u
    卜: p
    sm-0: p
    缶: c
    几: c
    鼠: l
    聿: d
    自: k
    毛: s
    sm-p: p
    厂: p
    sm-l: n
    大: u
    立: n
    力: g
    比: k
    舌: j
    寸: k
    心: e
    癶: l
    犬: j
    '1': e
    石: g
    女: m
    骨: o
    片: s
    土: l
    韦: j
    革: v
    小: c
    皮: p
    囗: l
    sm-h: c
    sm-w: m
    '4': o
    : m
    用: e
    镸: z
    歹: t
    食: i
    夂: p
    斗: g
    血: d
    丬: o
    勹: a
    彡: z
    雨: f
    鼻: v
    贝: r
    sm-b: h
    示: e
    sm-zh: s
    麦: k
    sm-y: k
    赤: j
    sm-k: z
    戈: d
    里: e
    艹: u
    方: l
    口: i
    纟: t
    麻: t
    丨: t
    丶: c
    彐: g
    罒: h
    门: l
    十: y
    母: k
    sm-r: g
    黑: o
    瓦: q
    又: k
    目: h
    卤: n
    辶: v
    覀: f
    隹: i
    足: c
    巛: s
    矢: q
    米: z
    一: d
    己: x
    见: f
    水: b
    鸟: c
    牛: r
    sm-c: r
    sm-d: d
    鬼: j
    爿: p
    sm-m: b
    辰: i
    八: h
    工: i
    犭: o
    户: c
    刀: o
    人: j
    日: o
    山: x
    sm-g: v
    sm-j: l
    父: j
    虍: c
    '5': a
    攵: n
    sm-f: r
    尸: e
    sm-t: x
    sm-q: t
    龙: d
    豕: i
    疋: e
    厶: n
    攴: e
    辛: d
    穴: c
    月: s
    冫: m
    王: x
    sm-s: y
    业: b
    sm-n: q
    页: y
    衣: w
    羽: d
    虫: v
    止: u
    白: i
    sm-ch: g
    宀: w
    二: g
    风: o
    丿: h
    乙: w
    尢: c
    豆: r
    爪: k
    豸: c
    弓: s
    斤: s
    走: m
    '2': i
    儿: t
    广: y
    田: d
    sm-z: w
    金: k
    马: c
    殳: s
    彳: n
    巾: z
    鹿: i
    禾: k
    子: i
    羊: p
    疒: l
    言: a
    鱼: h
    青: w
    火: g
  grouping: {}
encoder:
  max_length: 6
  auto_select_length: 2
  sources:
    s6:
      object:
        type: 字根
        rootIndex: -1
      next: null
    s1:
      object:
        type: 字根
        rootIndex: 1
      next: s2
    s4:
      object:
        type: 字根
        rootIndex: 4
      next: s5
    s0:
      object: null
      next: s1
    s5:
      object:
        type: 字根
        rootIndex: 5
      next: s6
    s2:
      object:
        type: 字根
        rootIndex: 2
      next: s3
    s3:
      object:
        type: 字根
        rootIndex: 3
      next: s4
  conditions: {}
  short_code_schemes:
  - prefix: 2
  - prefix: 3
  - prefix: 4
  - prefix: 5
  rules:
  - length_equal: 2
    formula: AaAbBaBb
  - length_equal: 3
    formula: AaBaCaCb
  - length_in_range:
    - 4
    - 10
    formula: AaBaCaZa
optimization:
  objective:
    characters_full:
      duplication: 1.0
    characters_short:
      tiers:
      - top: 500
        duplication: 1.0
        levels:
        - length: 2
          frequency: -10.0
      - duplication: 10.0
      duplication: 10.0
      key_distribution: 10.0
      pair_equivalence: 10.0
      levels:
      - length: 2
        frequency: -10.0
      - length: 3
        frequency: 1.0
      - length: 4
        frequency: 10.0
  constraints:
    elements:
    - element: 乙
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 一
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 丿
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 丨
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 丶
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: '1'
    - element: '2'
    - element: '3'
    - element: '4'
    - element: '5'
    - element: sm-q
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-w
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-r
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-t
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-y
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-p
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-s
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-d
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-f
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-g
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-h
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-j
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-k
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-l
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-z
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-x
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-c
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-b
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-n
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-m
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-sh
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-ch
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-zh
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-0
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
  metaheuristic:
    algorithm: SimulatedAnnealing
