version: 0.1.7
source: null
info:
  name: 二笔
  version: 0.1.0
  author: 无名氏
  description: 从模板创建
analysis:
  classifier: {}
  degenerator:
    feature:
      捺: 点
      提: 横
    no_cross: false
  selector:
  - 结构完整
  - 根少优先
  - 能连不交
  - 能散不连
  - 全符笔顺
  - 取大优先
form:
  alphabet: qwertyuiopasdfghjklzxcvbnm
  mapping:
    sm-m: m
    sm-k: k
    方: o
    耳: h
    疋: d
    大: g
    子: m
    食: i
    sm-q: q
    石: x
    攵: s
    皮: e
    sm-s: s
    宀: p
    乙: b
    巛: f
    又: d
    sm-l: l
    白: i
    艮: m
    金: n
    足: z
    其: k
    土: j
    血: k
    '1': e
    片: b
    心: g
    瓦: w
    厶: f
    穴: z
    爿: h
    辛: i
    里: c
    舌: i
    文: a
    尸: d
    八: f
    毛: z
    鼻: i
    王: f
    夕: r
    sm-p: p
    目: g
    黑: e
    人: l
    田: r
    斤: z
    自: i
    耒: e
    木: r
    sm-f: f
    : y
    彐: w
    麻: d
    小: s
    赤: e
    骨: k
    角: d
    '3': u
    比: o
    缶: j
    罒: x
    斗: d
    '2': i
    儿: w
    二: j
    广: t
    业: h
    音: e
    癶: n
    '5': a
    辰: i
    羽: f
    雨: x
    麦: p
    弓: a
    彳: n
    一: d
    卜: o
    女: a
    欠: o
    走: y
    几: f
    sm-t: t
    sm-ch: y
    刀: m
    鼠: o
    青: u
    己: q
    巾: c
    sm-w: w
    矢: p
    覀: c
    门: o
    殳: v
    勹: b
    身: y
    '4': o
    纟: c
    言: i
    冫: y
    囗: o
    鸟: q
    止: n
    丬: g
    爪: g
    镸: n
    sm-c: c
    力: e
    韦: q
    页: m
    鹿: r
    工: u
    sm-r: r
    贝: h
    牛: h
    艹: f
    户: r
    母: t
    攴: j
    口: w
    示: o
    豆: j
    丨: p
    sm-j: j
    瓜: i
    衣: z
    立: q
    丿: t
    丶: k
    车: b
    见: x
    用: f
    米: v
    舟: v
    羊: c
    sm-g: g
    sm-d: d
    父: o
    豕: r
    鱼: d
    sm-yi: k
    革: g
    月: s
    风: k
    夂: y
    sm-h: h
    sm-z: z
    马: s
    歹: t
    水: e
    尢: e
    虍: d
    sm-b: b
    戈: i
    气: n
    火: r
    sm-n: n
    辶: k
    彡: u
    sm-sh: s
    龙: c
    sm-zh: v
    犬: i
    卤: j
    厂: o
    虫: k
    寸: i
    山: q
    齿: e
    sm-x: x
    sm-yu: r
    sm-0: c
    疒: s
    十: v
    日: n
    隹: j
    聿: i
    鬼: e
    豸: d
    禾: g
    手: u
  grouping: {}
encoder:
  max_length: 6
  auto_select_length: 2
  sources:
    s5:
      object:
        type: 字根
        rootIndex: 5
      next: s6
    s2:
      object:
        type: 字根
        rootIndex: 2
      next: s3
    s1:
      object:
        type: 字根
        rootIndex: 1
      next: s2
    s6:
      object:
        type: 字根
        rootIndex: -1
      next: null
    s0:
      object: null
      next: s1
    s3:
      object:
        type: 字根
        rootIndex: 3
      next: s4
    s4:
      object:
        type: 字根
        rootIndex: 4
      next: s5
  conditions: {}
  short_code_schemes:
  - prefix: 2
  - prefix: 3
  - prefix: 4
  - prefix: 5
  rules:
  - length_equal: 2
    formula: AaAbBaBb
  - length_equal: 3
    formula: AaBaCaCb
  - length_in_range:
    - 4
    - 10
    formula: AaBaCaZa
optimization:
  objective:
    characters_full:
      duplication: 1.0
    characters_short:
      tiers:
      - top: 500
        duplication: 1.0
        levels:
        - length: 2
          frequency: -10.0
      - duplication: 10.0
      duplication: 10.0
      key_distribution: 10.0
      pair_equivalence: 20.0
      levels:
      - length: 2
        frequency: -10.0
      - length: 3
        frequency: 1.0
      - length: 4
        frequency: 10.0
  constraints:
    elements:
    - element: 乙
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 一
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 丿
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 丨
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: 丶
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: '1'
    - element: '2'
    - element: '3'
    - element: '4'
    - element: '5'
    - element: sm-q
    - element: sm-w
    - element: sm-r
    - element: sm-t
    - element: sm-p
    - element: sm-s
    - element: sm-d
    - element: sm-f
    - element: sm-g
    - element: sm-h
    - element: sm-j
    - element: sm-k
    - element: sm-l
    - element: sm-z
    - element: sm-x
    - element: sm-c
    - element: sm-b
    - element: sm-n
    - element: sm-m
    - element: sm-sh
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'x'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
    - element: sm-ch
      keys:
      - 'y'
    - element: sm-zh
      keys:
      - 'v'
    - element: sm-yi
      keys:
      - 'k'
    - element: sm-yu
      keys:
      - 'r'
    - element: sm-0
      keys:
      - 'q'
      - 'w'
      - 'r'
      - 't'
      - 'y'
      - 'p'
      - 's'
      - 'd'
      - 'f'
      - 'g'
      - 'h'
      - 'j'
      - 'k'
      - 'l'
      - 'z'
      - 'x'
      - 'c'
      - 'v'
      - 'b'
      - 'n'
      - 'm'
  metaheuristic:
    algorithm: SimulatedAnnealing
